domain_path: /media/user12/data/work/soc_2026_workspace/platform_fnd_cntr/export/platform_fnd_cntr/sw/standalone_microblaze_riscv_0
app_src_dir: /media/user12/data/tools/xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
lang: c
