set_property SRC_FILE_INFO {cfile:/media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_proc_sys_reset_0_0/soc_can_proc_sys_reset_0_0.xdc rfile:../../../SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_proc_sys_reset_0_0/soc_can_proc_sys_reset_0_0.xdc id:1 order:EARLY scoped_inst:soc_can_i/proc_sys_reset_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_clk_wiz_0/soc_can_clk_wiz_0.xdc rfile:../../../SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_clk_wiz_0/soc_can_clk_wiz_0.xdc id:2 order:EARLY scoped_inst:soc_can_i/clk_wiz/inst} [current_design]
set_property SRC_FILE_INFO {cfile:/media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_microblaze_riscv_0_0/soc_can_microblaze_riscv_0_0.xdc rfile:../../../SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_microblaze_riscv_0_0/soc_can_microblaze_riscv_0_0.xdc id:3 order:EARLY scoped_inst:soc_can_i/microblaze_riscv_0/U0} [current_design]
set_property SRC_FILE_INFO {cfile:/media/user12/data/work/SOC_exam_2026/SOC_exam_2026.srcs/constrs_1/imports/Downloads/Basys-3-Master.xdc rfile:../../../SOC_exam_2026.srcs/constrs_1/imports/Downloads/Basys-3-Master.xdc id:4} [current_design]
set_property SRC_FILE_INFO {cfile:/media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_mdm_1_0/soc_can_mdm_1_0.xdc rfile:../../../SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_mdm_1_0/soc_can_mdm_1_0.xdc id:5 order:LATE scoped_inst:soc_can_i/mdm_1/U0} [current_design]
current_instance soc_can_i/proc_sys_reset_0/U0
set_property src_info {type:SCOPED_XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -type CDC -id {CDC-11} -user "proc_sys_reset" -desc "Timing uncritical paths" -tags "1171415" -scope -internal -to [get_pins -quiet -filter REF_PIN_NAME=~*D -of_objects [get_cells -hierarchical -filter {NAME =~ */ACTIVE_LOW_AUX.ACT_LO_AUX/GENERATE_LEVEL_P_S_CDC.SINGLE_BIT.CROSS_PLEVEL_IN2SCNDRY_IN_cdc_to}]]
current_instance
current_instance soc_can_i/clk_wiz/inst
set_property src_info {type:SCOPED_XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_input_jitter [get_clocks -of_objects [get_ports clk_in1]] 0.100
current_instance
current_instance soc_can_i/microblaze_riscv_0/U0
set_property src_info {type:SCOPED_XDC file:3 line:4 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -scoped -user microblaze_riscv -tags IPCPG-502 -type CDC -id CDC-1  -description "Debug protocol ensures stable signals" -from [get_pins -quiet riscv_core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.*/C]
set_property src_info {type:SCOPED_XDC file:3 line:5 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -scoped -user microblaze_riscv -tags IPCPG-502 -type CDC -id CDC-3  -description "Debug protocol ensures stable signals" -from [get_pins -quiet riscv_core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.*/C]
set_property src_info {type:SCOPED_XDC file:3 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -scoped -user microblaze_riscv -tags IPCPG-502 -type CDC -id CDC-7  -description "Debug protocol ensures stable signals" -from [get_pins -quiet riscv_core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.*/C]
set_property src_info {type:SCOPED_XDC file:3 line:7 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -scoped -user microblaze_riscv -tags IPCPG-502 -type CDC -id CDC-10 -description "Debug protocol ensures stable signals" -from [get_pins -quiet riscv_core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.*/C]
set_property src_info {type:SCOPED_XDC file:3 line:8 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -scoped -user microblaze_riscv -tags IPCPG-502 -type CDC -id CDC-13 -description "Debug protocol ensures stable signals" -from [get_pins -quiet riscv_core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.*/C]
set_property src_info {type:SCOPED_XDC file:3 line:9 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -scoped -user microblaze_riscv -tags IPCPG-502 -type CDC -id CDC-15 -description "Debug protocol ensures stable signals" -from [get_pins -quiet riscv_core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.*/C]
set_property src_info {type:SCOPED_XDC file:3 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -scoped -user microblaze_riscv -tags IPCPG-502 -type CDC -id CDC-15 -description "Debug protocol ensures stable signals" -from [get_pins -quiet riscv_core_I/*.Core/*Debug_Logic.Master_Core.Debug*/*/C]
set_property src_info {type:SCOPED_XDC file:3 line:12 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -scoped -user microblaze_riscv -tags IPCPG-502 -type CDC -id CDC-1  -description "Debug protocol ensures stable signals" -to [get_pins -quiet riscv_core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.*/D]
set_property src_info {type:SCOPED_XDC file:3 line:13 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -scoped -user microblaze_riscv -tags IPCPG-502 -type CDC -id CDC-1  -description "Debug protocol ensures stable signals" -to [get_pins -quiet riscv_core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.*/CE]
set_property src_info {type:SCOPED_XDC file:3 line:14 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -scoped -user microblaze_riscv -tags IPCPG-502 -type CDC -id CDC-1  -description "Debug protocol ensures stable signals" -to [get_pins -quiet riscv_core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.*/*/D]
set_property src_info {type:SCOPED_XDC file:3 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -scoped -user microblaze_riscv -tags IPCPG-502 -type CDC -id CDC-7  -description "Debug protocol ensures stable signals" -to [get_pins -quiet riscv_core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.*/CLR]
set_property src_info {type:SCOPED_XDC file:3 line:16 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -scoped -user microblaze_riscv -tags IPCPG-502 -type CDC -id CDC-7  -description "Debug protocol ensures stable signals" -to [get_pins -quiet riscv_core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.*/PRE]
set_property src_info {type:SCOPED_XDC file:3 line:17 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -scoped -user microblaze_riscv -tags IPCPG-502 -type CDC -id CDC-15 -description "Debug protocol ensures stable signals" -to [get_pins -quiet riscv_core_I/*.Core/*Debug_Logic.Master_Core.Debug*/Serial_Dbg_Intf.*/CLR]
current_instance
set_property src_info {type:XDC file:4 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W7   IOSTANDARD LVCMOS33 } [get_ports {seg_0[0]}]
set_property src_info {type:XDC file:4 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W6   IOSTANDARD LVCMOS33 } [get_ports {seg_0[1]}]
set_property src_info {type:XDC file:4 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U8   IOSTANDARD LVCMOS33 } [get_ports {seg_0[2]}]
set_property src_info {type:XDC file:4 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V8   IOSTANDARD LVCMOS33 } [get_ports {seg_0[3]}]
set_property src_info {type:XDC file:4 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U5   IOSTANDARD LVCMOS33 } [get_ports {seg_0[4]}]
set_property src_info {type:XDC file:4 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V5   IOSTANDARD LVCMOS33 } [get_ports {seg_0[5]}]
set_property src_info {type:XDC file:4 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U7   IOSTANDARD LVCMOS33 } [get_ports {seg_0[6]}]
set_property src_info {type:XDC file:4 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V7   IOSTANDARD LVCMOS33 } [get_ports {seg_0[7]}]
set_property src_info {type:XDC file:4 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U2   IOSTANDARD LVCMOS33 } [get_ports {com_0[0]}]
set_property src_info {type:XDC file:4 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U4   IOSTANDARD LVCMOS33 } [get_ports {com_0[1]}]
set_property src_info {type:XDC file:4 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V4   IOSTANDARD LVCMOS33 } [get_ports {com_0[2]}]
set_property src_info {type:XDC file:4 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W4   IOSTANDARD LVCMOS33 } [get_ports {com_0[3]}]
set_property src_info {type:XDC file:4 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J1   IOSTANDARD LVCMOS33 } [get_ports {can_rx_port_0}];#Sch name = JA1
set_property src_info {type:XDC file:4 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L2   IOSTANDARD LVCMOS33 } [get_ports {can_tx_port_0}];#Sch name = JA2
set_property src_info {type:XDC file:4 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J2   IOSTANDARD LVCMOS33 } [get_ports {can_rx_port_1}];#Sch name = JA3
set_property src_info {type:XDC file:4 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G2   IOSTANDARD LVCMOS33 } [get_ports {can_tx_port_1}];#Sch name = JA4
set_property src_info {type:XDC file:4 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H1   IOSTANDARD LVCMOS33 } [get_ports {alarm_0}];#Sch name = JA7
current_instance soc_can_i/mdm_1/U0
set_property src_info {type:SCOPED_XDC file:5 line:15 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-10 -description "Debug protocol ensures stable signals" -from [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/*/C]
set_property src_info {type:SCOPED_XDC file:5 line:18 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -scoped -user mdm_riscv -tags IPCPG-503 -type METHODOLOGY -id TIMING-54 -object [get_clocks -quiet -of_objects [get_pins "Use*.BSCAN*/*/UPDATE"]] -description "Avoid warning for valid UPDATE clock constraint"
set_property src_info {type:SCOPED_XDC file:5 line:21 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -scoped -user mdm_riscv -tags IPCPG-503 -type METHODOLOGY -id TIMING-54 -object [get_clocks -quiet -of_objects [get_pins "Use*.BSCAN*/*/TCK"]] -description "Avoid warning for valid TCK clock constraint"
set_property src_info {type:SCOPED_XDC file:5 line:24 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -scoped -user mdm_riscv -tags IPCPG-503 -type METHODOLOGY -id TIMING-54 -object [get_clocks -quiet -of_objects [get_pins */*/*.BUFG_UPDATE/*/O]] -description "Avoid warning for valid UPDATE clock constraint"
set_property src_info {type:SCOPED_XDC file:5 line:29 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-1  -description "Debug protocol ensures stable signals" -from [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/*/C]
set_property src_info {type:SCOPED_XDC file:5 line:30 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-1  -description "Debug protocol ensures stable signals" -from [get_pins -quiet Use_E2.BSCAN_I/Use_E2.BSCANE2_I/INTERNAL_TDI]
set_property src_info {type:SCOPED_XDC file:5 line:31 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-1  -description "Debug protocol ensures stable signals" -from [get_pins -quiet Use_E2.BSCAN_I/Use_E2.BSCANE2_I/INTERNAL_TCK]
set_property src_info {type:SCOPED_XDC file:5 line:32 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-1  -description "Debug protocol ensures stable signals" -from [get_pins -quiet Use_E2.BSCAN_I/Use_E2.BSCANE2_I/UPDATE]
set_property src_info {type:SCOPED_XDC file:5 line:33 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-1  -description "Debug protocol ensures stable signals" -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/*/CE]
set_property src_info {type:SCOPED_XDC file:5 line:34 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-1  -description "Debug protocol ensures stable signals" -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/*/D]
set_property src_info {type:SCOPED_XDC file:5 line:35 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-1  -description "Debug protocol ensures stable signals" -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/*/R]
set_property src_info {type:SCOPED_XDC file:5 line:36 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-1  -description "Debug protocol ensures stable signals" -to [get_pins -quiet Use_JTAG_BSCAN.*/CE]
set_property src_info {type:SCOPED_XDC file:5 line:37 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-1  -description "Debug protocol ensures stable signals" -to [get_pins -quiet Use_JTAG_BSCAN.*/D]
set_property src_info {type:SCOPED_XDC file:5 line:38 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-1  -description "Debug protocol ensures stable signals" -to [get_pins -quiet Use_JTAG_BSCAN.*/R]
set_property src_info {type:SCOPED_XDC file:5 line:39 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-2  -description "Debug protocol ensures stable signals" -from [get_pins -quiet Use_E2.BSCAN_I/Use_E2.BSCANE2_I/INTERNAL_TCK]
set_property src_info {type:SCOPED_XDC file:5 line:40 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-7  -description "Debug protocol ensures stable signals" -from [get_pins -quiet Use_E2.BSCAN_I/Use_E2.BSCANE2_I/INTERNAL_TCK]
set_property src_info {type:SCOPED_XDC file:5 line:41 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-10 -description "Debug protocol ensures stable signals" -from [get_pins -quiet Use_E2.BSCAN_I/Use_E2.BSCANE2_I/INTERNAL_TCK]
set_property src_info {type:SCOPED_XDC file:5 line:42 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-11 -description "Debug protocol ensures stable signals" -from [get_pins -quiet Use_E2.BSCAN_I/Use_E2.BSCANE2_I/INTERNAL_TCK]
set_property src_info {type:SCOPED_XDC file:5 line:43 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-13 -description "Debug protocol ensures stable signals" -from [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/*/C]
set_property src_info {type:SCOPED_XDC file:5 line:44 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-13 -description "Debug protocol ensures stable signals" -from [get_pins -quiet Use_JTAG_BSCAN.*/C]
set_property src_info {type:SCOPED_XDC file:5 line:45 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-13 -description "Debug protocol ensures stable signals" -from [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/*/*/O]
set_property src_info {type:SCOPED_XDC file:5 line:46 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-13 -description "Debug protocol ensures stable signals" -from [get_pins -quiet Use_E2.BSCAN_I/Use_E2.BSCANE2_I/INTERNAL_TDI]
set_property src_info {type:SCOPED_XDC file:5 line:47 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-15 -description "Debug protocol ensures stable signals" -from [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/*/C]
set_property src_info {type:SCOPED_XDC file:5 line:48 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-15 -description "Debug protocol ensures stable signals" -from [get_pins -quiet Use_E2.BSCAN_I/Use_E2.BSCANE2_I/INTERNAL_TDI]
set_property src_info {type:SCOPED_XDC file:5 line:49 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-15 -description "Debug protocol ensures stable signals" -from [get_pins -quiet Use_E2.BSCAN_I/Use_E2.BSCANE2_I/INTERNAL_TCK]
set_property src_info {type:SCOPED_XDC file:5 line:50 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-15 -description "Debug protocol ensures stable signals" -from [get_pins -quiet Use_E2.BSCAN_I/Use_E2.BSCANE2_I/UPDATE]
set_property src_info {type:SCOPED_XDC file:5 line:51 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-15 -description "Debug protocol ensures stable signals" -to [get_pins -quiet MDM_Core_I1/JTAG_CONTROL_I/*/R]
set_property src_info {type:SCOPED_XDC file:5 line:52 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-15 -description "Debug protocol ensures stable signals" -to [get_pins -quiet Use_JTAG_BSCAN.*/R]
set_property src_info {type:SCOPED_XDC file:5 line:54 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-1  -description "Debug protocol ensures stable signals" -to [get_pins -quiet Internal_BSCANID.bscanid*reg/D]
set_property src_info {type:SCOPED_XDC file:5 line:55 export:INPUT save:INPUT read:READ} [current_design]
create_waiver -internal -quiet -user mdm_riscv -tags IPCPG-503 -type CDC -id CDC-1  -description "Debug protocol ensures stable signals" -to [get_pins -quiet Internal_BSCANID.bscanid*reg/CE]
