# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.srcs/sources_1/bd/soc_multiwatch_lcd/ip/soc_multiwatch_lcd_axi_gpio_0_0/soc_multiwatch_lcd_axi_gpio_0_0.xci
# IP: The module: 'soc_multiwatch_lcd_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_multiwatch_lcd/ip/soc_multiwatch_lcd_axi_gpio_0_0/soc_multiwatch_lcd_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_multiwatch_lcd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_multiwatch_lcd/ip/soc_multiwatch_lcd_axi_gpio_0_0/soc_multiwatch_lcd_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_multiwatch_lcd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_multiwatch_lcd/ip/soc_multiwatch_lcd_axi_gpio_0_0/soc_multiwatch_lcd_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_multiwatch_lcd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.srcs/sources_1/bd/soc_multiwatch_lcd/ip/soc_multiwatch_lcd_axi_gpio_0_0/soc_multiwatch_lcd_axi_gpio_0_0.xci
# IP: The module: 'soc_multiwatch_lcd_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_multiwatch_lcd/ip/soc_multiwatch_lcd_axi_gpio_0_0/soc_multiwatch_lcd_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_multiwatch_lcd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_multiwatch_lcd/ip/soc_multiwatch_lcd_axi_gpio_0_0/soc_multiwatch_lcd_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_multiwatch_lcd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_multiwatch_lcd/ip/soc_multiwatch_lcd_axi_gpio_0_0/soc_multiwatch_lcd_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_multiwatch_lcd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
