# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.srcs/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/soc_hello_axi_smc_0.xci
# IP: The module: 'soc_hello_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/bd_57e4.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_0/bd_57e4_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_1/bd_57e4_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_2/bd_57e4_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_3/bd_57e4_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_4/bd_57e4_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_5/bd_57e4_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_6/bd_57e4_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_7/bd_57e4_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_8/bd_57e4_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_9/bd_57e4_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_10/bd_57e4_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_11/bd_57e4_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_12/bd_57e4_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_1/bd_57e4_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_1/bd_57e4_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_5/bd_57e4_s00a2s_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_6/bd_57e4_sarn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_7/bd_57e4_srn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_8/bd_57e4_sawn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_9/bd_57e4_swn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_10/bd_57e4_sbn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_11/bd_57e4_m00s2a_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hello_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hello_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.srcs/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/soc_hello_axi_smc_0.xci
# IP: The module: 'soc_hello_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/bd_57e4.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_0/bd_57e4_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_1/bd_57e4_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_2/bd_57e4_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_3/bd_57e4_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_4/bd_57e4_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_5/bd_57e4_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_6/bd_57e4_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_7/bd_57e4_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_8/bd_57e4_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_9/bd_57e4_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_10/bd_57e4_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_11/bd_57e4_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_12/bd_57e4_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_1/bd_57e4_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_1/bd_57e4_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_5/bd_57e4_s00a2s_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_6/bd_57e4_sarn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_7/bd_57e4_srn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_8/bd_57e4_sawn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_9/bd_57e4_swn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_10/bd_57e4_sbn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/bd_0/ip/ip_11/bd_57e4_m00s2a_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hello_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hello_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
