# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.srcs/sources_1/bd/soc_hello/ip/soc_hello_clk_wiz_0/soc_hello_clk_wiz_0.xci
# IP: The module: 'soc_hello_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_clk_wiz_0/soc_hello_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hello_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_clk_wiz_0/soc_hello_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hello_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_clk_wiz_0/soc_hello_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hello_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.srcs/sources_1/bd/soc_hello/ip/soc_hello_clk_wiz_0/soc_hello_clk_wiz_0.xci
# IP: The module: 'soc_hello_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_clk_wiz_0/soc_hello_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hello_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_clk_wiz_0/soc_hello_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hello_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_hello/ip/soc_hello_clk_wiz_0/soc_hello_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_hello_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
