# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Basys-3-Master.xdc

# Block Designs: bd/soc_can/soc_can.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_can || ORIG_REF_NAME==soc_can} -quiet] -quiet

# IP: bd/soc_can/ip/soc_can_proc_sys_reset_0_0/soc_can_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_can_proc_sys_reset_0_0 || ORIG_REF_NAME==soc_can_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/soc_can/ip/soc_can_clk_wiz_0/soc_can_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_can_clk_wiz_0 || ORIG_REF_NAME==soc_can_clk_wiz_0} -quiet] -quiet

# IP: bd/soc_can/ip/soc_can_microblaze_riscv_0_0/soc_can_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_can_microblaze_riscv_0_0 || ORIG_REF_NAME==soc_can_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/soc_can/ip/soc_can_dlmb_v10_0/soc_can_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_can_dlmb_v10_0 || ORIG_REF_NAME==soc_can_dlmb_v10_0} -quiet] -quiet

# IP: bd/soc_can/ip/soc_can_ilmb_v10_0/soc_can_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_can_ilmb_v10_0 || ORIG_REF_NAME==soc_can_ilmb_v10_0} -quiet] -quiet

# IP: bd/soc_can/ip/soc_can_dlmb_bram_if_cntlr_0/soc_can_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_can_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==soc_can_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/soc_can/ip/soc_can_ilmb_bram_if_cntlr_0/soc_can_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_can_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==soc_can_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/soc_can/ip/soc_can_lmb_bram_0/soc_can_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_can_lmb_bram_0 || ORIG_REF_NAME==soc_can_lmb_bram_0} -quiet] -quiet

# IP: bd/soc_can/ip/soc_can_microblaze_riscv_0_axi_periph_imp_xbar_0/soc_can_microblaze_riscv_0_axi_periph_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_can_microblaze_riscv_0_axi_periph_imp_xbar_0 || ORIG_REF_NAME==soc_can_microblaze_riscv_0_axi_periph_imp_xbar_0} -quiet] -quiet

# IP: bd/soc_can/ip/soc_can_microblaze_riscv_0_axi_periph_0/soc_can_microblaze_riscv_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_can_microblaze_riscv_0_axi_periph_0 || ORIG_REF_NAME==soc_can_microblaze_riscv_0_axi_periph_0} -quiet] -quiet

# IP: bd/soc_can/ip/soc_can_microblaze_riscv_0_axi_intc_0/soc_can_microblaze_riscv_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_can_microblaze_riscv_0_axi_intc_0 || ORIG_REF_NAME==soc_can_microblaze_riscv_0_axi_intc_0} -quiet] -quiet

# IP: bd/soc_can/ip/soc_can_microblaze_riscv_0_xlconcat_0/soc_can_microblaze_riscv_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_can_microblaze_riscv_0_xlconcat_0 || ORIG_REF_NAME==soc_can_microblaze_riscv_0_xlconcat_0} -quiet] -quiet

# IP: bd/soc_can/ip/soc_can_mdm_1_0/soc_can_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_can_mdm_1_0 || ORIG_REF_NAME==soc_can_mdm_1_0} -quiet] -quiet

# IP: bd/soc_can/ip/soc_can_axi_uartlite_0_0/soc_can_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_can_axi_uartlite_0_0 || ORIG_REF_NAME==soc_can_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/soc_can/ip/soc_can_myip_CAN_controller_0_0/soc_can_myip_CAN_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_can_myip_CAN_controller_0_0 || ORIG_REF_NAME==soc_can_myip_CAN_controller_0_0} -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_proc_sys_reset_0_0/soc_can_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_can_proc_sys_reset_0_0 || ORIG_REF_NAME==soc_can_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_proc_sys_reset_0_0/soc_can_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_can_proc_sys_reset_0_0 || ORIG_REF_NAME==soc_can_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_clk_wiz_0/soc_can_clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_can_clk_wiz_0 || ORIG_REF_NAME==soc_can_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_clk_wiz_0/soc_can_clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_can_clk_wiz_0 || ORIG_REF_NAME==soc_can_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_clk_wiz_0/soc_can_clk_wiz_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_microblaze_riscv_0_0/soc_can_microblaze_riscv_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_can_microblaze_riscv_0_0 || ORIG_REF_NAME==soc_can_microblaze_riscv_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_microblaze_riscv_0_0/soc_can_microblaze_riscv_0_0_ooc_debug.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_dlmb_v10_0/soc_can_dlmb_v10_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_ilmb_v10_0/soc_can_ilmb_v10_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_dlmb_bram_if_cntlr_0/soc_can_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_ilmb_bram_if_cntlr_0/soc_can_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_lmb_bram_0/soc_can_lmb_bram_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_microblaze_riscv_0_axi_periph_imp_xbar_0/soc_can_microblaze_riscv_0_axi_periph_imp_xbar_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_microblaze_riscv_0_axi_intc_0/soc_can_microblaze_riscv_0_axi_intc_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_can_microblaze_riscv_0_axi_intc_0 || ORIG_REF_NAME==soc_can_microblaze_riscv_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_microblaze_riscv_0_axi_intc_0/soc_can_microblaze_riscv_0_axi_intc_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_can_microblaze_riscv_0_axi_intc_0 || ORIG_REF_NAME==soc_can_microblaze_riscv_0_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_microblaze_riscv_0_axi_intc_0/soc_can_microblaze_riscv_0_axi_intc_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_mdm_1_0/soc_can_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_can_mdm_1_0 || ORIG_REF_NAME==soc_can_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_mdm_1_0/soc_can_mdm_1_0_ooc_trace.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_axi_uartlite_0_0/soc_can_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_can_axi_uartlite_0_0 || ORIG_REF_NAME==soc_can_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_axi_uartlite_0_0/soc_can_axi_uartlite_0_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/ip/soc_can_axi_uartlite_0_0/soc_can_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_can_axi_uartlite_0_0 || ORIG_REF_NAME==soc_can_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_can/soc_can_ooc.xdc
