# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/soc_fnd/soc_fnd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_fnd || ORIG_REF_NAME==soc_fnd} -quiet] -quiet

# IP: bd/soc_fnd/ip/soc_fnd_proc_sys_reset_0_0/soc_fnd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_fnd_proc_sys_reset_0_0 || ORIG_REF_NAME==soc_fnd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/soc_fnd/ip/soc_fnd_clk_wiz_0/soc_fnd_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_fnd_clk_wiz_0 || ORIG_REF_NAME==soc_fnd_clk_wiz_0} -quiet] -quiet

# IP: bd/soc_fnd/ip/soc_fnd_microblaze_riscv_0_0/soc_fnd_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_fnd_microblaze_riscv_0_0 || ORIG_REF_NAME==soc_fnd_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/soc_fnd/ip/soc_fnd_dlmb_v10_0/soc_fnd_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_fnd_dlmb_v10_0 || ORIG_REF_NAME==soc_fnd_dlmb_v10_0} -quiet] -quiet

# IP: bd/soc_fnd/ip/soc_fnd_ilmb_v10_0/soc_fnd_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_fnd_ilmb_v10_0 || ORIG_REF_NAME==soc_fnd_ilmb_v10_0} -quiet] -quiet

# IP: bd/soc_fnd/ip/soc_fnd_dlmb_bram_if_cntlr_0/soc_fnd_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_fnd_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==soc_fnd_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/soc_fnd/ip/soc_fnd_ilmb_bram_if_cntlr_0/soc_fnd_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_fnd_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==soc_fnd_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/soc_fnd/ip/soc_fnd_lmb_bram_0/soc_fnd_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_fnd_lmb_bram_0 || ORIG_REF_NAME==soc_fnd_lmb_bram_0} -quiet] -quiet

# IP: bd/soc_fnd/ip/soc_fnd_mdm_1_0/soc_fnd_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_fnd_mdm_1_0 || ORIG_REF_NAME==soc_fnd_mdm_1_0} -quiet] -quiet

# IP: bd/soc_fnd/ip/soc_fnd_axi_uartlite_0_0/soc_fnd_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_fnd_axi_uartlite_0_0 || ORIG_REF_NAME==soc_fnd_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/soc_fnd/ip/soc_fnd_axi_smc_0/soc_fnd_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_fnd_axi_smc_0 || ORIG_REF_NAME==soc_fnd_axi_smc_0} -quiet] -quiet

# Block Designs: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/bd_d47b.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_0/bd_d47b_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_1/bd_d47b_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_2/bd_d47b_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_3/bd_d47b_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_4/bd_d47b_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_5/bd_d47b_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_6/bd_d47b_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_7/bd_d47b_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_8/bd_d47b_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_9/bd_d47b_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_10/bd_d47b_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_11/bd_d47b_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_12/bd_d47b_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_13/bd_d47b_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_14/bd_d47b_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_15/bd_d47b_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_16/bd_d47b_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_17/bd_d47b_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_18/bd_d47b_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_19/bd_d47b_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_20/bd_d47b_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_21/bd_d47b_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_22/bd_d47b_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_23/bd_d47b_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_24/bd_d47b_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_25/bd_d47b_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_26/bd_d47b_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_27/bd_d47b_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_28/bd_d47b_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_29/bd_d47b_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_30/bd_d47b_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_31/bd_d47b_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_32/bd_d47b_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_33/bd_d47b_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_34/bd_d47b_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_35/bd_d47b_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_36/bd_d47b_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_37/bd_d47b_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_38/bd_d47b_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_39/bd_d47b_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_40/bd_d47b_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_41/bd_d47b_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_42/bd_d47b_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_43/bd_d47b_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_44/bd_d47b_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_45/bd_d47b_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_46/bd_d47b_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/soc_fnd/ip/soc_fnd_axi_gpio_0_0/soc_fnd_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_fnd_axi_gpio_0_0 || ORIG_REF_NAME==soc_fnd_axi_gpio_0_0} -quiet] -quiet

# IP: bd/soc_fnd/ip/soc_fnd_axi_gpio_1_0/soc_fnd_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==soc_fnd_axi_gpio_1_0 || ORIG_REF_NAME==soc_fnd_axi_gpio_1_0} -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_proc_sys_reset_0_0/soc_fnd_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_fnd_proc_sys_reset_0_0 || ORIG_REF_NAME==soc_fnd_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_proc_sys_reset_0_0/soc_fnd_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_fnd_proc_sys_reset_0_0 || ORIG_REF_NAME==soc_fnd_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_clk_wiz_0/soc_fnd_clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_fnd_clk_wiz_0 || ORIG_REF_NAME==soc_fnd_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_clk_wiz_0/soc_fnd_clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_fnd_clk_wiz_0 || ORIG_REF_NAME==soc_fnd_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_clk_wiz_0/soc_fnd_clk_wiz_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_microblaze_riscv_0_0/soc_fnd_microblaze_riscv_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_fnd_microblaze_riscv_0_0 || ORIG_REF_NAME==soc_fnd_microblaze_riscv_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_microblaze_riscv_0_0/soc_fnd_microblaze_riscv_0_0_ooc_debug.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_lmb_bram_0/soc_fnd_lmb_bram_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_mdm_1_0/soc_fnd_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_fnd_mdm_1_0 || ORIG_REF_NAME==soc_fnd_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_mdm_1_0/soc_fnd_mdm_1_0_ooc_trace.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_uartlite_0_0/soc_fnd_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_fnd_axi_uartlite_0_0 || ORIG_REF_NAME==soc_fnd_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_uartlite_0_0/soc_fnd_axi_uartlite_0_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_uartlite_0_0/soc_fnd_axi_uartlite_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_fnd_axi_uartlite_0_0 || ORIG_REF_NAME==soc_fnd_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_1/bd_d47b_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_1/bd_d47b_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_2/bd_d47b_arinsw_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_3/bd_d47b_rinsw_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_4/bd_d47b_awinsw_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_5/bd_d47b_winsw_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_6/bd_d47b_binsw_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_7/bd_d47b_aroutsw_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_8/bd_d47b_routsw_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_9/bd_d47b_awoutsw_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_10/bd_d47b_woutsw_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_11/bd_d47b_boutsw_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_12/bd_d47b_arni_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_13/bd_d47b_rni_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_14/bd_d47b_awni_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_15/bd_d47b_wni_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_16/bd_d47b_bni_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_20/bd_d47b_s00a2s_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_21/bd_d47b_sarn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_22/bd_d47b_srn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_23/bd_d47b_sawn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_24/bd_d47b_swn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_25/bd_d47b_sbn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_26/bd_d47b_m00s2a_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_27/bd_d47b_m00arn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_28/bd_d47b_m00rn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_29/bd_d47b_m00awn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_30/bd_d47b_m00wn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_31/bd_d47b_m00bn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_33/bd_d47b_m01s2a_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_34/bd_d47b_m01arn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_35/bd_d47b_m01rn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_36/bd_d47b_m01awn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_37/bd_d47b_m01wn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_38/bd_d47b_m01bn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_40/bd_d47b_m02s2a_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_41/bd_d47b_m02arn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_42/bd_d47b_m02rn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_43/bd_d47b_m02awn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_44/bd_d47b_m02wn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/bd_0/ip/ip_45/bd_d47b_m02bn_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_fnd_axi_smc_0 || ORIG_REF_NAME==soc_fnd_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_gpio_0_0/soc_fnd_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_fnd_axi_gpio_0_0 || ORIG_REF_NAME==soc_fnd_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_gpio_0_0/soc_fnd_axi_gpio_0_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_gpio_0_0/soc_fnd_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_fnd_axi_gpio_0_0 || ORIG_REF_NAME==soc_fnd_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_gpio_1_0/soc_fnd_axi_gpio_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_fnd_axi_gpio_1_0 || ORIG_REF_NAME==soc_fnd_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_gpio_1_0/soc_fnd_axi_gpio_1_0_ooc.xdc

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/ip/soc_fnd_axi_gpio_1_0/soc_fnd_axi_gpio_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==soc_fnd_axi_gpio_1_0 || ORIG_REF_NAME==soc_fnd_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /media/user12/data/work/SOC_exam_2026/SOC_exam_2026.gen/sources_1/bd/soc_fnd/soc_fnd_ooc.xdc
