# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/user12/data/work/basys_exam_2025/basys_exam_2025.srcs/sources_1/ip/karina3_1/karina3.xci
# IP: The module: 'karina3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/user12/data/work/basys_exam_2025/basys_exam_2025.gen/sources_1/ip/karina3_1/karina3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'karina3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /media/user12/data/work/basys_exam_2025/basys_exam_2025.srcs/sources_1/ip/karina3_1/karina3.xci
# IP: The module: 'karina3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/user12/data/work/basys_exam_2025/basys_exam_2025.gen/sources_1/ip/karina3_1/karina3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'karina3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
